name: Rust-static-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone helix repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'helix-editor'
          repository: 'helix'

#       - name: Install latest rust toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           default: true
#           override: true
#           target: x86_64-unknown-linux-musl
      - name: Install rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
          
      - name: Install musl dependencies
        run: sudo apt-get install musl-dev musl-tools -y
        
      - name: Build
        run: rustup target add x86_64-unknown-linux-musl && cd helix && cargo build --target=x86_64-unknown-linux-musl --all --release && strip target/release/PROJECT_NAME && mv target/release/$PROJECT_NAME target/release/PROJECT_NAME_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            helix/target/x86_64-unknown-linux-musl/release/hx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
