name: Rust-static-build
on:
  push:
    tags: ['*']
    branches: [ '*' ]
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone helix repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'helix-editor'
          repository: 'helix'

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: x86_64-unknown-linux-musl
          
      - name: Install musl and other dependencies
        run: sudo apt-get install musl-dev musl-tools zip -y
        
      - name: Build helix
        run: cd helix &&
             rustup target add x86_64-unknown-linux-musl &&
             cargo install --path helix-term --target=x86_64-unknown-linux-musl &&
             strip $HOME/.cargo/bin/hx &&
             mkdir -p $HOME/.config/runtime &&
             cp --verbose -r ./runtime $HOME/.config/helix &&
             $HOME/.cargo/bin/hx --grammar fetch &&
             $HOME/.cargo/bin/hx --grammar build &&
             zip -r $HOME/runtime.zip $HOME/.config/helix/runtime
             
      - name: Install starship
        run: cargo install starship --target=x86_64-unknown-linux-musl

      - name: Install zellij
        run: cargo install zellij --target=x86_64-unknown-linux-musl

      - name: Install zoxide
        run: cargo install zoxide --target=x86_64-unknown-linux-musl
      
      - name: Install fd-find
        run: cargo install fd-find --target=x86_64-unknown-linux-musl

      - name: Install taplo
        run: cargo install taplo-lsp --target=x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/.cargo/bin/hx
            /home/runner/runtime.zip
            /home/runner/.cargo/bin/starship
            /home/runner/.cargo/bin/zellij
            /home/runner/.cargo/bin/zoxide
            /home/runner/.cargo/bin/fd
            /home/runner/.cargo/bin/taplo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
