name: Rust-static-build
on:
  push:
    tags: ['*']
    branches: [ '*' ]
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create alpine cargo directory
        run: |
          sudo mkdir /mnt/alpine-cargo
          sudo chown -R runner /mnt/alpine-cargo
          sudo mkdir /mnt/alpine-artifacts
          sudo chown -R runner /mnt/alpine-artifacts
      
      - name: Set up Alpine linux
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages:
            build-base
            pkgconfig
            lld
            git
            rustup
            zip
            cmake
          shell-name: alpine.sh
          volumes:
           - /mnt/alpine-cargo:/home/runner/.cargo
           - /mnt/alpine-artifacts:/home/runner/artifacts

      - name: Install Rust stable toolchain via rustup
        run: rustup-init --target x86_64-unknown-linux-musl --default-toolchain stable --profile minimal -y
        shell: alpine.sh {0}
        
      - name: Clone helix repo
        run: git clone https://github.com/helix-editor/helix.git
        shell: alpine.sh {0}
          
      - name: Build helix
        run: |
          pwd
          cd helix
          rustup target add x86_64-unknown-linux-musl
          cargo install --path helix-term --target=x86_64-unknown-linux-musl
          strip $HOME/.cargo/bin/hx
          zip -r $HOME/artifacts/hx-runtime.zip ./runtime
        shell: alpine.sh {0}
             
      - name: Install starship
        run: cargo install starship --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}
         
      - name: Install zellij
        run: cargo install zellij --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Install zoxide
        run: cargo install zoxide --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}
      
      - name: Install fd-find
        run: cargo install fd-find --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Install taplo
        run: cargo install taplo-cli --features=lsp --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /mnt/alpine-cargo/bin/hx
            /mnt/alpine-artifacts/hx-runtime.zip
            /mnt/alpine-cargo/bin/starship
            /mnt/alpine-cargo/bin/zellij
            /mnt/alpine-cargo/bin/zoxide
            /mnt/alpine-cargo/bin/fd
            /mnt/alpine-cargo/bin/taplo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
