name: Rust-static-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: hx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone helix repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'helix-editor'
        repository: 'helix'
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cd helix && cargo build --target $BUILD_TARGET --release
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}
        path: helix/target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}*
