name: Rust-static-build
on:
  push:
    tags: ['*']
    branches: [ '*' ]
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Alpine linux
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages:
            build-base
            pkgconfig
            lld
            git
            rustup
            zip
          shell-name: alpine.sh
          volumes: /home:/mnt/alpine

      - name: Install Rust stable toolchain via rustup
        run: rustup-init --target x86_64-unknown-linux-musl --default-toolchain stable --profile minimal -y
        shell: alpine.sh {0}
        
      - name: Clone helix repo
        run: git clone https://github.com/helix-editor/helix.git
        shell: alpine.sh {0}
          
      - name: Build helix
        run: |
          pwd
          cd helix
          rustup target add x86_64-unknown-linux-musl
          cargo install --path helix-term --target=x86_64-unknown-linux-musl
          strip $HOME/.cargo/bin/hx
          mkdir -p $HOME/.config/helix
          cp --verbose -r ./runtime $HOME/.config/helix/runtime
          zip -r $HOME/runtime.zip $HOME/.config/helix/runtime
        shell: alpine.sh {0}
             
      - name: Install starship
        run: cargo install starship --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}
         
      - name: Install zellij
        run: cargo install zellij --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Install zoxide
        run: cargo install zoxide --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}
      
      - name: Install fd-find
        run: cargo install fd-find --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Install taplo
        run: cargo install taplo-lsp --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/.cargo/bin/hx
            /home/runner/runtime.zip
            /home/runner/.cargo/bin/starship
            /home/runner/.cargo/bin/zellij
            /home/runner/.cargo/bin/zoxide
            /home/runner/.cargo/bin/fd
            /home/runner/.cargo/bin/taplo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
