name: Rust-static-build
on:
  push:
    tags: ['*']
    branches: [ '*' ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Clone helix repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'helix-editor'
          repository: 'helix'

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: x86_64-unknown-linux-musl
          
      - name: Install musl dependencies
        run: sudo apt-get install musl-dev musl-tools -y
        
      - name: Build
        run: cd helix &&
             rustup target add x86_64-unknown-linux-musl &&
             cargo install --path helix-term --target=x86_64-unknown-linux-musl &&
             strip $HOME/.cargo/bin/hx &&
             mkdir -p $HOME/.config/runtime &&
             cp -r ./runtime $HOME/.config/helix &&
             $HOME/.cargo/bin/hx --grammar fetch &&
             $HOME/.cargo/bin/hx --grammar build
             
      - name: Install starship
        run: cargo install starship --target=x86_64-unknown-linux-musl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/.cargo/bin/hx
            /home/runner/.cargo/bin/hx
            /home/runner/.config/helix
            /home/runner/.cargo/bin/starship
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
