name: Rust-static-build
on:
  push:
    tags: ['*']
    branches: [ '*' ]
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Alpine linux
        id: alpine-target
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86_64
          packages:
            build-base
            pkgconfig
            lld
            git
            rustup
            zip
            cmake
            gnupg
            ca-certificates
            python3
            libressl-dev
            freetype-dev
            alsa-lib-dev
            expat-dev
            libxcb-dev
            libbz2
            sndio-dev
            freeglut-dev
            libxmu-dev
            libxi-dev
            fontconfig-dev
            libxcursor-dev
            perl
          shell-name: alpine.sh

      - name: Install Rust stable toolchain via rustup
        run: rustup-init --target x86_64-unknown-linux-musl --default-toolchain stable --profile minimal -y
        shell: alpine.sh {0}
        
      - name: Clone helix repo
        run: git clone https://github.com/helix-editor/helix.git
        shell: alpine.sh {0}
          
      - name: Build helix
        run: |
          pwd
          cd helix
          rustup target add x86_64-unknown-linux-musl
          export RUSTFLAGS="-C target-feature=-crt-static"
          cargo install --path helix-term --target=x86_64-unknown-linux-musl
          strip $HOME/.cargo/bin/hx
          zip -r $HOME/hx-runtime.zip ./runtime
        shell: alpine.sh {0}

#       - name: Install neovide
#         run: cargo install --git https://github.com/neovide/neovide
#         shell: alpine.sh {0}
             
      - name: Install rust packages
        run: cargo install ripgrep starship zellij zoxide fd-find taplo-cli felix joshuto gitui  alacritty --target=x86_64-unknown-linux-musl
        shell: alpine.sh {0}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/hx
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/hx-runtime.zip
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/starship
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/zellij
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/zoxide
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/fd
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/taplo
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/fx
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/joshuto
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/gitui
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/alacritty
            ${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/rg
#${{ steps.alpine-target.outputs.root-path }}/home/runner/.cargo/bin/xplr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
